### ISSUE TITLE
remove nasm dependency

### ISSUE THREAD

**Issue by rain-1** [microkernel2018/bootloader#2]
could we build boot1.asm with `i686-elf-as` somehow? or translate it to GNU as syntax.

**Comment by rakesh491** [comment]
Ain't NASM much easier than GAS. I mean NASM is simple + we might require to write some low-level functions and GAS would be total mess.

**Comment by rain-1** [comment]
useful reference https://github.com/travisg/3x86/blob/master/bootblock.S#L135

**Comment by rain-1** [comment]
done! thanks @rakesh491
